# Introduction of Numpy and Review of Linear Algebra

Numpy is a scientific computing package or library in Python.

The package is mainly focus on using a multidimensional array object (vector, matrix, and tensor) and computing the arrays. 

Mathematical, logical, shape manipulation, basic linear algebra, basic statistical operations and much more operations are provided in Numpy.

In other words, It's a Python version of Matlab (and free!)


#### This Ipython notebook will cover basic linear algebra with numpy examples

To install Numpy on your computer please uncommend below cell and run it

In [1]:
# !pip install numpy

In [2]:
# To use numpy we need to import numpy
import numpy as np

#### What is Scalar, Vectors, Matrices and Tensor?
- Scalar

    A scalar is just a single number such as 1, 2, 5, or 10.5.
    
    We can make a int or flot varialbe as a Scalar


In [3]:
Scalar = 3

- Vectors
    A vector is an array of numbers orders. The first element of vector **_x_**  is x<sub>1</sub>, the second element is x<sub>2</sub> and so on <br>
    
   The vector **_x_** is
    $$\begin{bmatrix} x_1 \\ x_2 \\ \vdots \\ x_n \end{bmatrix} \tag{1}$$
    


Let's make a vector with numpy

In [4]:
Vector = np.array([1,2, 3 ])
print(Vector)

[1 2 3]


- A Matrix is a 2-D array of numbers. e.g
    $$\begin{bmatrix} x_{1,1} & x_{1,2} & x_{1,3} \\ x_{2,1} & x_{2,2} & x_{2,3}\end{bmatrix} \tag{2}$$



An example of 2-D array with numpy

In [5]:
Matrix = np.array([[1,2],[3,4],[5,6]])
print(Matrix)

[[1 2]
 [3 4]
 [5 6]]


- A Tensor is an array that has more than two axes.


An example of 3-D array with numpy

In [6]:
Tensor = np.array([[[1,2],[3,4],[5,6]],
                   [[7,8],[9,10],[11,12]]])
print(Tensor)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


Useful Matrix Constructors

We can construct some special matrix with numpy such as all elements are zeros, ones, or particular number, and the identity matrix

In [7]:
print("2 x 2 matrix with zeros \n", np.zeros((2,2)))
print("2 x 2 matrix with ones \n",np.ones((2,2)))
print("2 x 2 matrix with 7 \n", np.full((2,2), 7))
print("2 x 2 identity matrix \n", np.eye(2))


2 x 2 matrix with zeros 
 [[0. 0.]
 [0. 0.]]
2 x 2 matrix with ones 
 [[1. 1.]
 [1. 1.]]
2 x 2 matrix with 7 
 [[7 7]
 [7 7]]
2 x 2 identity matrix 
 [[1. 0.]
 [0. 1.]]


Array Math

In [8]:
x = np.array([[1, 2],[3, 4]], dtype=np.int)
y = np.array([[5, 6],[7, 8]], dtype=np.float32)

In [9]:
# Elementwise sum
print(x + y)
print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [10]:
# Elementwise difference;
print(x - y)
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [11]:
# Elementwise product;
print(x * y)
print(np.multiply(x, y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [12]:
# Elementwise division;
print(x / y)
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [13]:
# Elementwise square root;
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


#### The dot and cross product

Let u as a vector and M as a 3 x 3 Matrix

In [14]:
u = np.array([1,2,3])
M = np.random.rand(3, 4)
M_1 = np.random.rand(3, 3)
M_2 = np.random.rand(3, 3)
print(M)

[[0.63624784 0.46267602 0.88561099 0.48392408]
 [0.71154441 0.78145191 0.78005536 0.44685288]
 [0.69464154 0.87950164 0.73650787 0.50314767]]


The dot product of two vectors will yield a scalar.
The dot product of two matrices will yield a matrix.

The dot product of vecotrs should have the same shape.
The dot product of matrix should match the number of columns in the first matrix and the number of rows in the second matrix. <br>
To match the two numbers we can transpose Matrix


Dot product of (3,2) and (2,3) and it will yield (3,3) Matrix

In [15]:
print("dot product of u \n", np.dot(u, u.T))
print("Transpose of the M shape is \n", M.T.shape)
print("dot product of M and M.T \n", np.dot(M, M.T))

dot product of u 
 14
Transpose of the M shape is 
 (4, 3)
dot product of M and M.T 
 [[1.63736976 1.72134612 1.74463323]
 [1.72134612 1.9251264  1.98090643]
 [1.74463323 1.98090643 2.05165141]]


Cross Product <br>

Please note Cross product of A and B $\neq$ Cross product of B and A

In [16]:
print("Cross product of M_1 and M_2 \n", np.cross(M_1, M_2))
print("Cross product of M_2 and M_1 \n", np.cross(M_2, M_1))

Cross product of M_1 and M_2 
 [[-0.39128168  0.1304457   0.48449931]
 [-0.27651887  0.2900005  -0.09035968]
 [ 0.63831773  0.00369058 -0.32752032]]
Cross product of M_2 and M_1 
 [[ 0.39128168 -0.1304457  -0.48449931]
 [ 0.27651887 -0.2900005   0.09035968]
 [-0.63831773 -0.00369058  0.32752032]]


### Determenant

2 x 2 matrix

$$det \begin{bmatrix} a & b \\ c & d  \\\end{bmatrix}  = ad- bc$$

3 x 3 matrix

$$det \begin{bmatrix}a & b & c \\ d & e & f \\ g & h & i \end{bmatrix}  = a \cdot \begin {vmatrix} e & f \\ g & h \end{vmatrix} - b \cdot \begin {vmatrix} d & f \\ g &i \end{vmatrix} + c \cdot \begin{vmatrix} d & e \\ g & h \end{vmatrix} $$

In numpy let's use numpy.linalg library

In [23]:
print("M_1 : \n", M_1)

print("determinant of M_1 is", np.linalg.det(M_1))

M_1 : 
 [[0.96398472 0.51103789 0.64092323]
 [0.05665529 0.15903573 0.33703289]
 [0.06150979 0.75885387 0.12842989]]
determinant of M_1 is -0.19869676141617124


### Inverse
M_1<sup>-1</sup>M_1 = I <br>
Where I is Identity Matrix <br>

In numpy you can use np.linalg.inv(M_1)

In [24]:
print(np.linalg.inv(M_1))

[[ 1.18438656 -2.11747051 -0.3538401 ]
 [-0.06771419 -0.42467427  1.45237831]
 [-0.16714331  3.52340772 -0.62585325]]


##### What if the matrix is not a square matirx? <br>
Use the psuedo inverse function

np.linagle.pinv()

In [26]:
np.linalg.pinv(M)

array([[ -1.65020616,   8.11948112,  -6.09766662],
       [ -1.89643362,   0.17573368,   1.87164874],
       [  1.24506233,   1.8391808 ,  -2.47552498],
       [  3.77070217, -14.20906519,  10.75791134]])

## Solve Ax = b

using numpy.linalg.solve() function

$$\begin{bmatrix}1 & 1 & 1 \\0 & 2 & 5 \\2 & 5 & -1\end{bmatrix} \begin{bmatrix}x \\y \\z \end{bmatrix} = \begin{bmatrix}6 \\-4 \\27 \end{bmatrix}$$
If these three matrices are called A, X and B. Then The X = A<sup>-1</sup>B


In [17]:
A = np.array([[1,1,1], [0,2,5], [2,5,-1]])
B = np.array([6,-4,27]).T

In [18]:
np.inner(np.linalg.inv(A), B)

array([ 5.,  3., -2.])

In [19]:
# Let's try using numpy.linagl.solve()
np.linalg.solve(A, B)

array([ 5.,  3., -2.])